// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crqrphgbbdycxmgltkxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNycXJwaGdiYmR5Y3htZ2x0a3h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMTIyMTcsImV4cCI6MjA3MjY4ODIxN30.XZaCWgyMllEsz2BUTt-pIfmr2sJlUQcBoKtDAXvhYCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});